controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Fallback homepage if needed
home:
    path: /
    controller: App\Controller\JobController::home
